/**
 * Write taoot/src/movie-lines.json: which films play which puppet lines (#50).
 *
 *   npx tsx taoot/tools/mkmovielines.ts
 *
 * A film's frames and click regions can each name a sound, and many of those
 * sounds are a puppet's voice line by its ident — `zeit.mov`'s second frame
 * plays `penny1.132`, Penny's "A German colonel named Zeitel…", out of the
 * film's own sound table. The words are the puppet line's, so they can be
 * captioned from the puppet in every edition; what the game cannot say at run
 * time without reading every puppet first is WHICH puppet a sound's name
 * belongs to. This is that table, read once from the English tree: names only,
 * no text.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { readMovFile } from "@dreamfactory/engine/df/mov";
import { readPupFile } from "@dreamfactory/engine/df/pup";
import { gamefiles } from "./gamefiles";

const g = gamefiles(undefined, "en");
/** line ident → the puppet file it is in */
const owner = new Map<string, string>();
for (const f of g.names(/\.pup$/i)) {
  try {
    for (const l of readPupFile(new Uint8Array(readFileSync(g.resolve(f)!))).dialogue.values()) {
      if (l.audioLocation) owner.set(l.ident.toLowerCase(), f.toLowerCase());
    }
  } catch {
    /* a puppet that will not read owns no lines */
  }
}

const films: Record<string, Record<string, string>> = {};
for (const f of g.names(/\.mov$/i)) {
  let mov;
  try {
    mov = readMovFile(new Uint8Array(readFileSync(g.resolve(f)!)));
  } catch {
    continue;
  }
  for (const seg of mov.segments) {
    const sounds = new Set<string>();
    for (const frame of seg.frames) {
      if (frame.sound) sounds.add(frame.sound.toLowerCase());
      for (const r of (frame as { regions?: { sound?: string }[] }).regions ?? []) if (r.sound) sounds.add(r.sound.toLowerCase());
    }
    for (const s of sounds) {
      const pup = owner.get(s);
      if (pup) (films[f.toLowerCase()] ??= {})[s] = pup;
    }
  }
}

const sorted = Object.fromEntries(Object.entries(films).sort(([a], [b]) => a.localeCompare(b)));
const out = new URL("../src/movie-lines.json", import.meta.url);
writeFileSync(
  out,
  JSON.stringify(
    {
      about: "Generated by taoot/tools/mkmovielines.ts from the English tree: film -> { frame sound -> the puppet whose line it is }. Names only; the words are read from the puppet at run time (#50).",
      films: sorted,
    },
    null,
    1,
  ) + "\n",
);
console.log(`${Object.keys(sorted).length} films, ${Object.values(sorted).reduce((a, b) => a + Object.keys(b).length, 0)} sounds`);
