/**
 * armchairfeet: an imported mesh, baked by `taoot/tools/bedsitglb.ts`. Do not edit —
 * re-run the tool. In the room's own frame: +x is the back, y is the length
 * about 0, z is up from the floor, stretched to the measured
 * 1720 x 1100 x 1580 the whole piece is known to be.
 *
 * 297 triangles, 178 vertices, positions quantized to 16 bits over
 * {@link BOX}. Normals are not stored: `Builder.mesh` averages them from the
 * triangles, which is both smaller here and smoother there.
 */

/** the box the vertices occupy, in the piece's own frame — what a chart laid
 *  over this mesh measures itself against */
export const BOX = {
  lo: [-512.3, -584.5, 0.0] as const,
  hi: [428.0, 574.4, 155.8] as const,
};

/** base64 of the packed vertices, then of the triangle indices */
const PACKED = "6BBDFuYUThCFFeYUuBJ9GP//NQF9GMb67RM7Gcb6gxHHFOYUUhO/F8b6gxHwBeYU7RO+AMb6gxEyBeYU7RMAAMb6ThB0BOYUuBIAAMb6BQMyBeYUNQG+AP//agJ0BKwPAAC+AMb60AHwBawPAAA6Asb60AHHFKwPAAC/F8b6agJDFuYUmwB9GP//BQOFFeYUnwOFFawP6BCFFXMKgxGFFXMK6BDHFHMKOgTHFDkFnwPHFDkFagKFFXMKagIJFHMK0AHwBXMKagIyBawPBQOuBjkFOgSuBnMKThAJFDkFgxHHFHMKHRLHFHMKHRLwBXMKgxEyBXMK6BAyBXMKnwMyBTkFThCuBjkFgxHwBXMK+vwyBeYUKvsyBeYUYPwyBawPyv4AAP//d+sAAP//ZP++AP//lf3wBeYU//98Acb6ZP8BF///YPzHFOYUZP99GMb6YPyFFawPyv59GMb6xftDFuYUL/59GMb6rexDFuYUd+s7Gf//EuyFFeYUQuo7Gf//d+vHFOYUqOm/F///EuzwBeYUQup8Acb6EuwyBeYU3eoAAMb6R+10BOYUR+0yBawPrewyBXMKEuzwBawPd+vHFHMKEuyFFXMKrezHFHMKrexDFnMKKvuFFXMKxfuFFXMKxfvHFHMK+vwyBXMKxfuuBnMKxfsyBXMKR+2uBnMKEuzwBXMK4u0JFHMK9fkJFHMKKvuuBjkFKvvHFHMK///E5sb6+vy86eYU///+6Mb6xft66uYUyv6C58b6R+286awPd+uC5///QurE5v//rex66uYUQupA6P//d+s46+YUEuxR+awPQuqD/v//EuzN+qwPQur//8b6R+3N+uYUd+v/////xfvN+qwPyv7//8b6+vzN+qwPZP9B/8b6+vxR+awP//+D/sb6lf046+YUZP+L+8b6+vw463MK+vx66nMKxft66nMKYPw46zkFKvv263MKxfuT+DkFYPxR+XMKYPwP+jkFYPzN+jkFKvtR+TkF4u046zkFR+166nMKrey86awPrex66nMKEuw466wPrew463MK4u1R+XMKR+0P+nMKrewP+nMKrexR+TkF6BDN+nMKnwMP+nMKBQPN+qwP0AFB/8b6mwBB////uBL//8b6gxEP+uYU7RP//8b67ROD/sb6gxE466wP7RNA6Mb6gxF66qwPiBSC58b66BC86eYUUhOC54z1BQN66uYUbwWC58b6NQGC58b6agJ66uYUmwCC58b60AE466wPmwD+6Mb6agIP+uYUAADF/cb6BQPN+uYUBQMP+nMKBQNR+XMKagI463MKagJ66nMKBQP26zkFnwN66jkF6BB66jkFgxF66nMKHRI463MKgxH263MKHRJR+XMKHRIP+nMK6BBR+TkFThD26wAAOgT26zkF1QST+DkFsw9R+TkF6BAP+nMK";
const INDEX = "AAABAAIAAQADAAIAAgAEAAAABAAFAAAABAAGAAUABgAHAAUABgAIAAcACAAJAAcACAAKAAkACgALAAkACgAMAAsADAANAAsADAAOAA0ADgAPAA0ADgAQAA8AEAARAA8AEAASABEAEgATABEAEgAUABMAFAAVABMAFAAWABUAFgAXABUAFgADABcAAwABABcAAQAYABcAAQAZABgAAQAAABkAAAAaABkAAAAFABoAGgAbABkAGwAYABkAGwAcABgAHAAdABgAHQAeABgAHgAXABgAHgAVABcAHgAfABUAHgAdAB8AHwATABUAHwAgABMAIAARABMAIAAhABEAIQAPABEAIAAiACEAIAAfACIAHwAdACIAHQAjACIAHQAcACMAHAAkACMAHAAbACQAGwAlACQAGwAaACUAGgAmACUAGgAFACYABQAHACYABwAnACYABwAJACcACQAoACcACQALACgACwApACgACwANACkADQAqACkADQAPACoADwAhACoAIQAiACoAIgAjACoAIwArACoAKwApACoAIwAkACsAJAAsACsALAApACsALAAoACkALAAnACgALAAmACcALAAlACYALAAkACUALQAuAC8ALQAwAC4AMAAxAC4ALQAyADAALQAzADIAMwA0ADIAMwA1ADQAMwA2ADUANgA3ADUANgA4ADcAOAA5ADcAOAA6ADkAOgA7ADkAOgA8ADsAPAA9ADsAPAA+AD0APgA/AD0APgBAAD8AQABBAD8AQABCAEEAQgBDAEEAQgBEAEMARABFAEMARABGAEUARgAxAEUARgAuADEARgBHAC4ARgBIAEcARgBEAEgARABJAEgARABCAEkAQgBAAEkAQABKAEkAQAA+AEoAPgBLAEoAPgA8AEsASwBMAEoASwBNAEwASwA8AE0APABOAE0APAA6AE4AOgBPAE4AOgA4AE8AOABQAE8AOAA2AFAANgAzAFAAMwBRAFAAMwAtAFEALQAvAFEALwBSAFEALwBTAFIALwAuAFMALgBHAFMARwBUAFMARwBVAFQARwBIAFUASABJAFUASQBKAFUASgBMAFUATABUAFUATABWAFQATABNAFYATQBXAFYATQBOAFcAVwBYAFYAWABUAFYAWABTAFQAWABSAFMAWABZAFIAWABXAFkAVwBOAFkATgBPAFkATwBQAFkAUABRAFkAUQBSAFkAWgBbAFwAWgBdAFsAWgBeAF0AXgBfAF0AXgBgAF8AYABhAF8AYQBiAF8AYQBjAGIAYwBkAGIAYwBlAGQAYwBmAGUAZgBnAGUAZgBoAGcAaABpAGcAaABqAGkAagBrAGkAagBsAGsAbABtAGsAbABuAG0AbgBvAG0AbgBwAG8AcABxAG8AcAByAHEAcgBcAHEAXABbAHEAWwBzAHEAWwB0AHMAWwBdAHQAXQB1AHQAXQBfAHUAdQB2AHQAdgBzAHQAdQB3AHYAdgB4AHMAdgB3AHgAeAB5AHMAeQBxAHMAeQBvAHEAeQB6AG8AegBtAG8AegB7AG0AegB5AHsAeQB4AHsAeAB8AHsAeAB3AHwAdwB9AHwAdwB1AH0AdQB+AH0AdQBfAH4AXwB/AH4AXwBiAH8AYgCAAH8AgAB+AH8AYgBkAIAAZACBAIAAZABlAIEAgQCCAIAAggB+AIAAggB9AH4AggCDAH0AgwB8AH0AgwCEAHwAhAB7AHwAhABrAHsAawBtAHsAhABpAGsAhACFAGkAhACDAIUAhQBnAGkAhQCGAGcAhQCDAIYAgwCCAIYAggCBAIYAgQBlAIYAZQBnAIYAhwCIAIkAiQCKAIcAiQCLAIoAigCMAIcAjACNAIcAjACOAI0AjgCPAI0AjwCQAI0AjwCRAJAAkQCSAJAAkQCTAJIAkwCUAJIAkwCVAJQAlQCWAJQAlQCXAJYAlwCYAJYAmACZAJYAmACaAJkAmgCbAJkAmgCcAJsAnACdAJsAnACeAJ0AngCfAJ0AngCLAJ8AiwCJAJ8AiQCgAJ8AiQCIAKAAoAChAJ8AoACIAKEAoQCdAJ8AoQCiAJ0AogCbAJ0AogCjAJsAowCZAJsAogCkAKMAogChAKQApAClAKMApQCZAKMApQCWAJkApQCmAJYApgCUAJYApgCnAJQApwCSAJQApwCoAJIAqACQAJIApwCpAKgApwCmAKkAqQCqAKgAqgCQAKgAqgCNAJAAqgCrAI0AqgCsAKsAqgCpAKwAqQCtAKwAqQCmAK0ApgCuAK0ApgClAK4ApQCkAK4ApAChAK4AoQCvAK4ArwCtAK4AoQCIAK8ArwCwAK0ArwCIALAAsACsAK0AsACxAKwAsACIALEAsQCrAKwAsQCNAKsAsQCHAI0AsQCIAIcA";

function bytes(s: string): Uint16Array {
  const bin = atob(s), n = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) n[i] = bin.charCodeAt(i);
  return new Uint16Array(n.buffer);
}

const packed = bytes(PACKED);
export const POSITION = new Float32Array(packed.length);
for (let i = 0; i < packed.length; i += 3) {
  for (let c = 0; c < 3; c++) POSITION[i + c] = BOX.lo[c] + (packed[i + c] / 65535) * (BOX.hi[c] - BOX.lo[c]);
}
export const INDICES = bytes(INDEX);
