/**
 * packclosed: an imported mesh, baked by `taoot/tools/bedsitglb.ts`. Do not edit —
 * re-run the tool. In the room's own frame: +x is the back, y is the length
 * about 0, z is up from the floor, at the file's own coordinates taken as metres at 1.549375 units to one.
 *
 * 256 triangles, 172 vertices, positions quantized to 16 bits over
 * {@link BOX}. Normals are not stored: `Builder.mesh` averages them from the
 * triangles, which is both smaller here and smoother there.
 *
 * Texture coordinates ARE stored: they are the file's own, and nothing here
 * could work them out again.
 */

/** the box the vertices occupy, in the piece's own frame — what a chart laid
 *  over this mesh measures itself against */
export const BOX = {
  lo: [-61.5, -83.8, 0.0] as const,
  hi: [61.5, 83.8, 30.0] as const,
};

/** base64 of the packed vertices, then of the triangle indices */
const PACKED = "igWcBAAAhwWvAqkDtQMrA34FTgPABPQDWwKkBDQNRgO0Av4MeALABC3hZwPvAlfh0wNQA9foaQPBBIDqigVj+wAATgM/+/QDtQPU/H4FhwVQ/akDWwJb+zQNRgNL/f4MeAI/+y3hbgMg+2zq1AO2/NfoYgMu/VbhdfqcBAAAsfzABPQDSvwrA34FePqvAqkDpP2kBDQNufy0Av4Mh/3ABC3hkfzfBGzqK/xJA9fonfzRAlbhpP1b+zQNtfxe+94DSvzO/H4FtPws/f8Mdfpj+wAAefoy/b8Dh/0/+y3hnfwu/VbhK/y2/Nfokfwg+2zqIAMAgAAA6gAAgPEDAAAAgHMNUwPbAj13YwKsBEN3cwEAgDLufQAAgLrkUwMk/T13YwJT+0N3AIA3/AAAAIAB/sUDnP1T+0N3rPwk/T133/wAgAAAFf8AgPED//8AgHMNjP4AgDLugv8AgLrkrPzbAj13nP2sBEN3AIDIAwAAAID+AcUDAIAAgAAAJgAAgGN52f8AgGN5igpC/5whkgo6/0R3/3/x//B3AID//84hoQoq/9XMAIDV/+nNXvUq/9XMbfU6/0R3dfVC/5whgAZv/j53kwZc/o7deAZ4/s0QAIAP/8nebPlc/o7df/lv/j53h/l4/s0QAIBB/+gQfwVH/soMhwVQ/akDtQPU/H4FRgNL/f4MmwUq/ozhYgMu/Vbh1AO2/NfopgUx/a/qgPpH/soMtPws/f8MSvzO/H4Fefoy/b8DZPoq/ozhWfox/a/qK/y2/Nfonfwu/VbhhwU//j13UwMk/T13AIAB/sUDAIAU/98MAIDI/e7rAIDf/tDirPwk/T13ePo//j13dfW9AJwhbfXFAER3AIAOAPB3AIAAAM4hXvXVANXMAIAqAOnNoQrVANXMkgrFAER3igq9AJwhf/mQAT53bPmjAY7dh/mHAc0QAIDwAMnekwajAY7dgAaQAT53eAaHAc0QAIC+AOgQfwW4AcoMRgO0Av4MtQMrA34FhwWvAqkDmwXVAYzhpQXtAprq0wNQA9foZwPvAlfhgPq4AcoMePqvAqkDSvwrA34Fufy0Av4MZPrVAYzhnfzRAlbhK/xJA9foWfrOAq/qhwXAAT13UwPbAj13ePrAAT13rPzbAj13AID+AcUDAIDrAN8MAIA3Au7rAIAgAdDiqwW8BGXuaQPBBIDq0wNQA9fopQXtAprqqwVD+2XupgUx/a/q1AO2/NfobgMg+2zqVPq8BGXuWfrOAq/qK/xJA9fokfzfBGzqVPpD+2Xukfwg+2zqK/y2/NfoWfox/a/qsgMAgD7ycwEAgDLuAID6+8nvAIDI/e7rTfwAgD7yjP4AgDLuAIAFBMnvAIA3Au7rAIAAgP//";
const INDEX = "AAABAAIAAAACAAMABAADAAIABAACAAUABgAHAAgABgAIAAkACgALAAwACgAMAA0ADgAPAAwADgAMAAsAEAARABIAEAASABMAFAAVABYAFAAWABcAGAAZABYAGAAWABUAGgAbABwAGgAcAB0AHgAfACAAHgAgACEAIgAjACAAIgAgAB8AJAAlACYAJAAmACcACgAoACkACgApAAsACwApACoACwAqAA4AKAAAAAMAKAADACkAKQADAAQAKQAEACoABQArACwABQAsAAQAKwAHAAYAKwAGACwACQAtAC4ACQAuAAYALQARABAALQAQAC4AEwAvADAAEwAwABAALwAPAA4ALwAOADAAIgAxADIAIgAyACMAMQAKAA0AMQANADIAJAAzADQAJAA0ACUAMwAeACEAMwAhADQAFAA1ADYAFAA2ABUAFQA2ADcAFQA3ABgANQAiAB8ANQAfADYANgAfAB4ANgAeADcAJwA4ADkAJwA5ACQAOAAbABoAOAAaADkAHQA6ADsAHQA7ABoAOgAZABgAOgAYADsAAAA8AD0AAAA9AAEAPAAUABcAPAAXAD0AKAA+ADwAKAA8AAAABAAsAD8ABAA/ACoALAAGAC4ALAAuAD8ACgAxAD4ACgA+ACgAKgA/ADAAKgAwAA4APwAuABAAPwAQADAAPgA1ABQAPgAUADwANwBAADsANwA7ABgAQAA5ABoAQAAaADsAHgAzAEAAHgBAADcAMQAiADUAMQA1AD4AMwAkADkAMwA5AEAAQQBCAEMAQQBDAEQAQgBFAEYAQgBGAEMAQwBGAEcAQwBHAEgARABDAEgARABIAEkASgBLAEUASgBFAEIATABKAEIATABCAEEATQBOAEcATQBHAEYASwBNAEYASwBGAEUATwBQAEkATwBJAEgATgBPAEgATgBIAEcAUQBMAEEAUQBBAEQAUABRAEQAUABEAEkAUgBTAFQAUgBUAFUAVgBXAFgAVgBYAFkAWgBbAFwAWgBcAF0AXgBfAGAAXgBgAGEAVgBiAGMAVgBjAFcAYgBSAFUAYgBVAGMAXQBkAGUAXQBlAFoAZABTAFIAZABSAGUAWQBmAGcAWQBnAFYAZgBfAF4AZgBeAGcAYQBoAGkAYQBpAF4AaABbAFoAaABaAGkAZQBSAEwAZQBMAFEAUgBiAEoAUgBKAEwAVgBnAE0AVgBNAEsAYgBWAEsAYgBLAEoAWgBlAFEAWgBRAFAAaQBaAFAAaQBQAE8AZwBeAE4AZwBOAE0AXgBpAE8AXgBPAE4AagBrAGwAagBsAG0AawBuAG8AawBvAGwAbABvAHAAbABwAHEAbQBsAHEAbQBxAHIAcwB0AG4AcwBuAGsAdQBzAGsAdQBrAGoAdgB3AHAAdgBwAG8AdAB2AG8AdABvAG4AeAB5AHIAeAByAHEAdwB4AHEAdwBxAHAAegB1AGoAegBqAG0AeQB6AG0AeQBtAHIAewB8AH0AewB9AH4AfwCAAIEAfwCBAIIAgwCEAIUAgwCFAIYAhwCIAIkAhwCJAIoAewCLAIwAewCMAHwAiwB/AIIAiwCCAIwAhwCNAI4AhwCOAIgAjQCDAIYAjQCGAI4AfgCPAJAAfgCQAHsAjwCEAIMAjwCDAJAAigCRAJIAigCSAIcAkQCAAH8AkQB/AJIAewCQAHoAewB6AHkAiwB7AHkAiwB5AHgAfwCLAHgAfwB4AHcAkgB/AHcAkgB3AHYAkACDAHUAkAB1AHoAgwCNAHMAgwBzAHUAhwCSAHYAhwB2AHQAjQCHAHQAjQB0AHMAkwCUAJUAkwCVAJYAlwCYAJkAlwCZAJoAmwCcAJ0AmwCdAJ4AnwCgAKEAnwChAKIAkwCjAKQAkwCkAJQAowCXAJoAowCaAKQAlwClAKYAlwCmAJgApQCfAKIApQCiAKYAnwCnAKgAnwCoAKAApwCbAJ4ApwCeAKgAmwCpAKoAmwCqAJwAqQCTAJYAqQCWAKoAqwCjAJMAqwCTAKkApQCXAKMApQCjAKsApwCrAKkApwCpAJsAnwClAKsAnwCrAKcA";
/** and of the texture coordinates the file came with, over [0, 1] */
const TEXCOORD = "AN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3mYmAN5mJgDeZiYA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVoAN71aADe9WgA3vVo17dD+4C5Pvsyua/83LcS/de3vATbt84CMrlJA3y53wQqBEP7JgQx/c8CtvyFAiD7KgS8BIUC3wTPAkkDJgTOAku5AIDxugCAAF4FBABeNwK2AgCAEAEAgABe+vsAXsj9AF4AgA==";

function bytes(s: string): Uint16Array {
  const bin = atob(s), n = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) n[i] = bin.charCodeAt(i);
  return new Uint16Array(n.buffer);
}

const packed = bytes(PACKED);
export const POSITION = new Float32Array(packed.length);
for (let i = 0; i < packed.length; i += 3) {
  for (let c = 0; c < 3; c++) POSITION[i + c] = BOX.lo[c] + (packed[i + c] / 65535) * (BOX.hi[c] - BOX.lo[c]);
}
export const INDICES = bytes(INDEX);

/** the atlas coordinates, one pair a vertex — pass to `Builder.mesh` and it
 *  uses these instead of box-mapping the material it is drawn in */
const texel = bytes(TEXCOORD);
export const UV = new Float32Array(texel.length);
for (let i = 0; i < texel.length; i++) UV[i] = texel[i] / 65535;
