/**
 * counterstripe: an imported mesh, baked by `taoot/tools/bedsitglb.ts`. Do not edit —
 * re-run the tool. In the room's own frame: +x is the back, y is the length
 * about 0, z is up from the floor, stretched to the measured
 * 1732 x 364 x 627 the whole piece is known to be.
 *
 * 240 triangles, 150 vertices, positions quantized to 16 bits over
 * {@link BOX}. Normals are not stored: `Builder.mesh` averages them from the
 * triangles, which is both smaller here and smoother there.
 */

/** the box the vertices occupy, in the piece's own frame — what a chart laid
 *  over this mesh measures itself against */
export const BOX = {
  lo: [-919.7, -871.7, 285.2] as const,
  hi: [-555.2, 860.0, 912.0] as const,
};

/** base64 of the packed vertices, then of the triangle indices */
const PACKED = "zg3SAwAABDwAACUC5jmPArEnowkwAwgmeGt+ADQCFGpIAgMoSZw0Aq8C95p0ADUoaco7AukCrMisAKooZPqUAgkDDfgdAcQoizhqAnNNswfFAidMUGhhAqtN1ZZpAvVNvca8AohO6vcNAYdOADbPAC9zNAeYASpy0GTUAHJzyJTKAshzj8ZRAjN0QPe7AAB05zLtAv+Y7AIsAyGYiGOyAmKZ0pPkAp6Z3cX9AqWZwfZVAoeZ7zG9BTa9pwAsBYm9+mLtBR+9j5P9BSi9a8XuBVW9s/a2BGS/rDGuC8ffPgC0C3PfrWK0C9zf4JOeCwrgo8SaCwzgAfakCo3hejEwFWj3AABYFRv1kWI5FaP32ZM0FcL38MQuFbr3GvYfFdr3dTP8IvT6IQI0I/X2CmQLI6n66ZQKI8/68MUJI7j6Q/fhIoD7STTiMB34GgUEMcf2+GTqMIP3vZXvMJ34NMfJMEb8KvjXMFz5gzW2PoL3sgXaPhD3lGa3Pib3Z5fKPlr3VMi/PrH3l/ifPh/4NjaHTKL3kwWtTBH3NWd6TDP3BJiOTFX3fsiBTBr4bPl1TAT6rzdPWsv3Ewd/WgP3w2g6WjL3iZlJWjr3JMo4Wuv3vvoOWpv9WzghaPD3qghGaBb362gFaGf3xJkBaLv3csoRaHv4J/sLaMH9NToNdqL7FAkWdgX3s2rpdaz8d5nOdVr98srTda78+PrAdYn4szrYg4j7dwnjg1z3I2v6gwr86JrPgyH9ZsuIg1389fuxg/H85zmUkeT6nQiykV73yGq1kdT6eJvakUj8zMuYkbL8/fukkZP7vThon5j33QiFnwL3dmp8nwT7oZuBnx36sMuXnw78BP2Dn7H59zksrYL62AhdrQP3rGo4rf/5aJtKrST6vMxQrcz56v1ArVf6ATsMu8371gk5u1n3Pmv1ukT6LpwOu+/5AM0Su9D6zP78umn6zzvlyHL32gsOyeL2HW3VyL76u53byBj6hM3gyM77NP/YyJb6Pz3N1sH7nAzp1uv26G3A1hT3cZ2t1vH2cc201hX3mP6X1tr6jz6s5N/7WA7A5G/21m6F5NP22Z9/5LH64c585IH7fv6c5CX7cD5u8nD20Axt8in4tW9f8m/5X59p8oz3+88z8tL7//858rn6MT7/////zg3/////k27/////9p7/////WM//////u///////";
const INDEX = "AAABAAIAAAACAAMAAQAEAAUAAQAFAAIABAAGAAcABAAHAAUABgAIAAkABgAJAAcACAAKAAsACAALAAkAAwACAAwAAwAMAA0AAgAFAA4AAgAOAAwABQAHAA8ABQAPAA4ABwAJABAABwAQAA8ACQALABEACQARABAADQAMABIADQASABMADAAOABQADAAUABIADgAPABUADgAVABQADwAQABYADwAWABUAEAARABcAEAAXABYAEwASABgAEwAYABkAEgAUABoAEgAaABgAFAAVABsAFAAbABoAFQAWABwAFQAcABsAFgAXAB0AFgAdABwAGQAYAB4AGQAeAB8AGAAaACAAGAAgAB4AGgAbACEAGgAhACAAGwAcACIAGwAiACEAHAAdACMAHAAjACIAHwAeACQAHwAkACUAHgAgACYAHgAmACQAIAAhACcAIAAnACYAIQAiACgAIQAoACcAIgAjACkAIgApACgAJQAkACoAJQAqACsAJAAmACwAJAAsACoAJgAnAC0AJgAtACwAJwAoAC4AJwAuAC0AKAApAC8AKAAvAC4AKwAqADAAKwAwADEAKgAsADIAKgAyADAALAAtADMALAAzADIALQAuADQALQA0ADMALgAvADUALgA1ADQAMQAwADYAMQA2ADcAMAAyADgAMAA4ADYAMgAzADkAMgA5ADgAMwA0ADoAMwA6ADkANAA1ADsANAA7ADoANwA2ADwANwA8AD0ANgA4AD4ANgA+ADwAOAA5AD8AOAA/AD4AOQA6AEAAOQBAAD8AOgA7AEEAOgBBAEAAPQA8AEIAPQBCAEMAPAA+AEQAPABEAEIAPgA/AEUAPgBFAEQAPwBAAEYAPwBGAEUAQABBAEcAQABHAEYAQwBCAEgAQwBIAEkAQgBEAEoAQgBKAEgARABFAEsARABLAEoARQBGAEwARQBMAEsARgBHAE0ARgBNAEwASQBIAE4ASQBOAE8ASABKAFAASABQAE4ASgBLAFEASgBRAFAASwBMAFIASwBSAFEATABNAFMATABTAFIATwBOAFQATwBUAFUATgBQAFYATgBWAFQAUABRAFcAUABXAFYAUQBSAFgAUQBYAFcAUgBTAFkAUgBZAFgAVQBUAFoAVQBaAFsAVABWAFwAVABcAFoAVgBXAF0AVgBdAFwAVwBYAF4AVwBeAF0AWABZAF8AWABfAF4AWwBaAGAAWwBgAGEAWgBcAGIAWgBiAGAAXABdAGMAXABjAGIAXQBeAGQAXQBkAGMAXgBfAGUAXgBlAGQAYQBgAGYAYQBmAGcAYABiAGgAYABoAGYAYgBjAGkAYgBpAGgAYwBkAGoAYwBqAGkAZABlAGsAZABrAGoAZwBmAGwAZwBsAG0AZgBoAG4AZgBuAGwAaABpAG8AaABvAG4AaQBqAHAAaQBwAG8AagBrAHEAagBxAHAAbQBsAHIAbQByAHMAbABuAHQAbAB0AHIAbgBvAHUAbgB1AHQAbwBwAHYAbwB2AHUAcABxAHcAcAB3AHYAcwByAHgAcwB4AHkAcgB0AHoAcgB6AHgAdAB1AHsAdAB7AHoAdQB2AHwAdQB8AHsAdgB3AH0AdgB9AHwAeQB4AH4AeQB+AH8AeAB6AIAAeACAAH4AegB7AIEAegCBAIAAewB8AIIAewCCAIEAfAB9AIMAfACDAIIAfwB+AIQAfwCEAIUAfgCAAIYAfgCGAIQAgACBAIcAgACHAIYAgQCCAIgAgQCIAIcAggCDAIkAggCJAIgAhQCEAIoAhQCKAIsAhACGAIwAhACMAIoAhgCHAI0AhgCNAIwAhwCIAI4AhwCOAI0AiACJAI8AiACPAI4AiwCKAJAAiwCQAJEAigCMAJIAigCSAJAAjACNAJMAjACTAJIAjQCOAJQAjQCUAJMAjgCPAJUAjgCVAJQA";

function bytes(s: string): Uint16Array {
  const bin = atob(s), n = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) n[i] = bin.charCodeAt(i);
  return new Uint16Array(n.buffer);
}

const packed = bytes(PACKED);
export const POSITION = new Float32Array(packed.length);
for (let i = 0; i < packed.length; i += 3) {
  for (let c = 0; c < 3; c++) POSITION[i + c] = BOX.lo[c] + (packed[i + c] / 65535) * (BOX.hi[c] - BOX.lo[c]);
}
export const INDICES = bytes(INDEX);
