/**
 * pendantwings: an imported mesh, baked by `taoot/tools/bedsitglb.ts`. Do not edit —
 * re-run the tool. In the room's own frame: +x is the back, y is the length
 * about 0, z is up from the floor, stretched to the measured
 * 760 x 760 x 660 the whole piece is known to be.
 *
 * 225 triangles, 158 vertices, positions quantized to 16 bits over
 * {@link BOX}. Normals are not stored: `Builder.mesh` averages them from the
 * triangles, which is both smaller here and smoother there.
 */

/** the box the vertices occupy, in the piece's own frame — what a chart laid
 *  over this mesh measures itself against */
export const BOX = {
  lo: [-380.0, -380.0, 230.3] as const,
  hi: [380.0, 380.0, 660.0] as const,
};

/** base64 of the packed vertices, then of the triangle indices */
const PACKED = "Xo1+xTZj7X9/2/QpiX//451DHoz+vpFRvor+taU7dX9+1NkYDoD+z4wSfok+sNgrsX/+yDQHooD+vpoDvob+pD8V1oB+shUBeoMenWcFHXw+nWcFdX4+srgAeXg+pLUUAX9+w64EMXW+r9grkXM+tY47eX//2iIqoXF+vr9RgXD+xXRmQW9+y9d/sX9/6spfgW5+0cWZ6X9/8RWDAW7+1O+t3o5+0iuWbo/+03SnHpD/13W5PpB/2xHP7X9/9zetfpD/3jvjwW1/2QbK0X9//RvUAW5/3oPiuXl/9AjzXoV/9AjzZX//////ToD/////7o1+yvVzPo7+zoaEPpzqgsMFPrFlfhUBHpy1fMMF/qMheYcUfrMGgRUB/rvhfuICfq5hdpgpfsgpf+wH/rOxdM84/sIigK4EvqN+hocUfq5uiYEpfszpfz4M/rM+i3w5fs5JfwYQ/tSdfysd/9sdf8Uuf9zhfwovPr7ejStV/+N1fx1Ifse+j7dw/szekK+Gf+lVf19lf+89f5qFftL+kSKjf/UJfzet/9e+kkPEf/tZfxvUf9y+kVrgf/M2hgjzf9xBbRLh/9fBbEPEftLhbWmi/sxBb6+GfsdhcP9vPr5RcnJUf/JZeAjz//+df//////dfv//AAAWgY7+AAR+gBvUAAA6gP//gA2JeQjzAA1uh5fxACOekhLhgCPhbcvhAApmgKiuAChhbUPEgBAegFOGgS1hbiKjgCcek0PEAS2ekSKjgBZSgDFlATNekAuHgTNBb6+GgBs+gDFJAThRcKNvwUGRcjBTgCMGgLcvwUzxdKw4ACNigIQxATgOjzJuwUHujIxTACoCgMoeATJhf04PAVIxdt8oATlRfx8GgTIagGgOQUzeihQ5wVEOiWwoATsGgAsFAVwmhqATAUvCgBUBoWOqggsFAU9BfgAAoWORfGcFQVzpeCsUQUcxfikCnpEBLdqjToCAD3t/koCAFgdaIXGBLzabkXABK4mx4W+AJk7JEoAACeWo4W6AIYPivpEAJyXH8X+AAzrRfpEAIoPiLoYADHn0eXoADAjzqX8AAI7+poAAAP//AXKBNqN4ToAAHcs+4XPBQONVfpABNoV7Xo6BQONVVoCAJZooXozBSvY7OoCAJbQnYXWBSiQ8HoCBL/wTBoABN+wHoXZBUB0srX+BPj4DUXlBW5sVBX9BTxUBhXyBYmcFkoHBThUB4oOBYq4EnodBW+MU9oABP+ICqoABODQHjopBUB0shoABLdkY";
const INDEX = "AAABAAIAAAADAAEAAwAEAAEABAAFAAEABAAGAAUABAAHAAYABgAIAAUABgAHAAgABwAJAAgABwAKAAkACgALAAkACgAMAAsADAANAAsADQAOAAsADgAJAAsADQAPAA4ADgAQAAkADgAPABAAEAAIAAkADwARABAAEQAIABAAEQAFAAgAEQASAAUAEgATAAUAEwABAAUAEgAUABMAFAAVABMAFQACABMAAgABABMAFQAWAAIAFgAXAAIAFgAYABcAGAAZABcAGAAaABkAGQAbABcAGwACABcAGQAcABsAGQAdABwAGQAeAB0AGQAfAB4AGQAaAB8AHwAgAB4AGgAhAB8AIQAiAB8AIgAgAB8AIQAjACIAIwAkACIAIwAgACQAIAAlACQAIAAiACUAJAAmACIAJAAlACYAJgAnACIAJwAlACIAJwAmACUAKAAAAAIAAgAbACgAGwApACgAKgArACwAKwAtACwAKgAuACsAKwAvAC0AKwAuAC8ALwAwAC0ALwAxADAAMQAyADAALwAzADEALwAuADMALgA0ADMALgAqADQANAA1ADMANQA2ADMANgAxADMANQA3ADYANgA4ADEAOAAyADEANgA5ADgAOQAyADgANgA3ADkAOQA6ADIANwA7ADkAOwA6ADkANwA8ADsAPAA9ADsAPQA6ADsAPAA+AD0APgA/AD0APwBAAD0APwBBAEAAPwBCAEEAQgBDAEEAQgBEAEMARABFAEMARABGAEUARgBHAEUARgBIAEcARQBIAEMASABJAEMASQBBAEMASQBKAEEASgBAAEEASgBLAEAASwA9AEAASwBMAD0ATABNAD0ATQA6AD0ATQAyADoATgBIAEUATgBHAEgATwBFAEcARwBOAE8ATwBQAEUAUABOAEUAUABPAE4AUQBSAFMAUgBUAFMAUwBVAFEAUwBUAFUAVQBWAFEAVQBUAFYAVgBSAFEAUgBXAFQAVwBWAFQAVgBYAFIAWABXAFIAWABZAFcAWABaAFkAWgBbAFkAWABcAFoAWABWAFwAXABdAFoAXQBeAFoAXgBbAFoAXQBfAF4AXgBgAFsAXwBhAF4AYQBgAF4AYQBiAGAAYQBjAGIAYQBkAGMAZABlAGMAYQBmAGQAYQBnAGYAYQBfAGcAZwBoAGYAaABpAGYAaQBkAGYAaQBlAGQAaQBqAGUAagBrAGUAagBsAGsAagBtAGwAagBpAG0AaQBuAG0AaQBoAG4AbgBvAG0AbwBwAG0AcABsAG0AbwBxAHAAcQByAHAAcQBzAHIAcwB0AHIAcwB1AHQAdQB2AHQAdgB3AHQAdwByAHQAdwBwAHIAdwBsAHAAdwBrAGwAdwB2AGsAeAB5AHoAeQB7AHoAeQB8AHsAeQB9AHwAeQB+AH0AeQB4AH4AfgB/AH0AeACAAH4AgACBAH4AgQB/AH4AgACCAIEAgwCCAH8AgwCBAIIAfwCEAIMAgQCFAH8AhQCEAH8AhQCGAIQAhgCDAIQAhQCBAIYAgQCDAIYAhwB6AHsAhwCIAHoAhwCJAIgAiACKAHoAigB4AHoAiACLAIoAiACMAIsAjACNAIsAiACOAIwAiACJAI4AiQCPAI4AjwCQAI4AjwCRAJAAjwCSAJEAkgCTAJEAkgCUAJMAlACVAJMAlACWAJUAlgCXAJUAlgCYAJcAmACZAJcAmQCaAJcAmgCVAJcAmgCTAJUAmgCbAJMAmgCZAJsAmwCRAJMAmQCcAJsAnACdAJsAnQCRAJsAnQCQAJEAnQCOAJAAnQCMAI4AnQCNAIwAnQCcAI0A";

function bytes(s: string): Uint16Array {
  const bin = atob(s), n = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) n[i] = bin.charCodeAt(i);
  return new Uint16Array(n.buffer);
}

const packed = bytes(PACKED);
export const POSITION = new Float32Array(packed.length);
for (let i = 0; i < packed.length; i += 3) {
  for (let c = 0; c < 3; c++) POSITION[i + c] = BOX.lo[c] + (packed[i + c] / 65535) * (BOX.hi[c] - BOX.lo[c]);
}
export const INDICES = bytes(INDEX);
