/**
 * desk: an imported mesh, baked by `taoot/tools/bedsitglb.ts`. Do not edit —
 * re-run the tool. In the room's own frame: +x is the back, y is the length
 * about 0, z is up from the floor, stretched to the measured
 * 2580 x 1110 x 1400 the whole piece is known to be.
 *
 * 320 triangles, 206 vertices, positions quantized to 16 bits over
 * {@link BOX}. Normals are not stored: `Builder.mesh` averages them from the
 * triangles, which is both smaller here and smoother there.
 */

/** the box the vertices occupy, in the piece's own frame — what a chart laid
 *  over this mesh measures itself against */
export const BOX = {
  lo: [-540.7, -1290.0, 0.0] as const,
  hi: [555.0, 1290.0, 1400.0] as const,
};

/** base64 of the packed vertices, then of the triangle indices */
const PACKED = "AQGKAFn2AADXSsP4AQFMSln2AAAAAMP45izXSsP46C1MSln25iw3uMP46C3CuFn2AAA3uMP4AQHCuFn2AAD//8P4AQF1/1n25iz//8P46C11/1n2/////8P4//91/1n2//8AAMP4//+KAFn25iwAAMP46C2KAFn2WwSASP//WwRXAv//QTGASP//QTGOuv//WwSOuv//WwSo/f//QTGo/f////+o/f////9XAv//QTFXAv//XAUyB1RM///2R1RM//8yB1RMXAX2R1RMXAUyB1n2///2R1n2XAX2R1n2//8yB1n2XAUYu1RM///N+FRM//8Yu1RMXAXN+FRMXAUYu1n2///N+Fn2XAXN+Fn2//8Yu1n2QzL2R1RM//+iVVRM///2R1RMQzKiVVRMQzL2R1n2//+iVVn2QzKiVVn2///2R1n2QzLnqlRM//8Yu1RM///nqlRMQzIYu1RMQzLnqln2//8Yu1n2QzIYu1n2///nqln2AUGiVSfW///nqifW//+iVSfWAUHnqifWAUGiVVn2///nqln2AUHnqln2//+iVVn2nfaiVQAA///nqgAA//+iVQAAnfbnqgAAnfaiVSfW///nqifWnfbnqifW//+iVSfWnzeiVZbUAUHnqpbUAUGiVZbUnzfnqpbUnzeiVVn2AUHnqln2nzfnqln2AUGiVVn2AUHKVzTYQ/O/qDTYQ/PKVzTYAUG/qDTYAUHKV7vyQ/O/qLvyAUG/qLvyQ/PKV7vyrgJFEadlvg6kQ6dlvg5FEadlrgKkQ6dlrgJFEe2evg6kQ+2ergKkQ+2evg5FEe2evg5uE0VpAcF8QUVpAcFuE0Vpvg58QUVpvg5uE0+bAcF8QU+bvg58QU+bAcFuE0+brgJFEQe0vg6kQwe0vg5FEQe0rgKkQwe0rgJFEbDpvg6kQ7DprgKkQ7Dpvg5FEbDpvg5uE6a3AcF8Qaa3AcFuE6a3vg58Qaa3vg5uExLmAcF8QRLmvg58QRLmAcFuExLmrgJqv6dlvg4R8adlvg5qv6dlrgIR8adlrgJqv+2evg4R8e2ergIR8e2evg5qv+2evg6SwUVpAcHo7kVpAcGSwUVpvg7o7kVpvg6SwU+bAcHo7k+bvg7o7k+bAcGSwU+brgJqvwe0vg4R8Qe0vg5qvwe0rgIR8Qe0rgJqv7Dpvg4R8bDprgIR8bDpvg5qv7Dpvg6Swaa3AcHo7qa3AcGSwaa3vg7o7qa3vg6SwRLmAcHo7hLmvg7o7hLmAcGSwRLm/TC3CQAA//+iVQAA//+3CQAA/TCiVQAA/TC3CYIe//+iVYIe/TCiVYIe//+3CYIe/SNRBIIe//+iVYIe//9RBIIe/SOiVYIe/SNRBPos//+iVfos/SOiVfos//9RBPosOSuOB/os//+iVfos//+OB/osOSuiVfosOSuOB1RM//+iVVRMOSuiVVRM//+OB1RM/TDnqgAA//9N9AAA///nqgAA/TBN9AAA/TDnqoIe//9N9IIe/TBN9IIe///nqoIe/SPnqoIe///H+oIe///nqoIe/SPH+oIe/SPnqvos///H+vos/SPH+vos///nqvosOSvnqvos///n9/os///nqvosOSvn9/osOSvnqlRM///n91RMOSvn91RM///nqlRM";
const INDEX = "AAABAAIAAAADAAEAAgAEAAUAAgABAAQABQAGAAcABQAEAAYABwAIAAkABwAGAAgACQAKAAsACQAIAAoACwAMAA0ACwAKAAwADQAOAA8ADQAMAA4ADwAQABEADwAOABAAEQASABMAEQAQABIAEwADAAAAEwASAAMAAwAUAAEAAwAVABQAAQAWAAQAAQAUABYABAAXAAYABAAWABcABgAYAAgABgAXABgACAAZAAoACAAYABkACgAaAAwACgAZABoADAAbAA4ADAAaABsADgAcABAADgAbABwAEAAdABIAEAAcAB0AEgAVAAMAEgAdABUAEwACAAUAEwAAAAIABwALAA0ABwAJAAsAEwAPABEADwAHAA0ABQAPABMADwAFAAcAFQAWABQAFQAdABYAGAAaABkAGAAXABoAHAAWAB0AFwAbABoAHAAXABYAFwAcABsAHgAfACAAHgAhAB8AIgAjACQAIgAlACMAHgAkACEAHgAiACQAIQAjAB8AIQAkACMAHwAlACAAHwAjACUAIAAiAB4AIAAlACIAJgAnACgAJgApACcAKgArACwAKgAtACsAJgAsACkAJgAqACwAKQArACcAKQAsACsAJwAtACgAJwArAC0AKAAqACYAKAAtACoALgAvADAALgAxAC8AMgAzADQAMgA1ADMALgA0ADEALgAyADQAMQAzAC8AMQA0ADMALwA1ADAALwAzADUAMAAyAC4AMAA1ADIANgA3ADgANgA5ADcAOgA7ADwAOgA9ADsANgA8ADkANgA6ADwAOQA7ADcAOQA8ADsANwA9ADgANwA7AD0AOAA6ADYAOAA9ADoAPgA/AEAAPgBBAD8AQgBDAEQAQgBFAEMAPgBEAEEAPgBCAEQAQQBDAD8AQQBEAEMAPwBFAEAAPwBDAEUAQABCAD4AQABFAEIARgBHAEgARgBJAEcASgBLAEwASgBNAEsARgBMAEkARgBKAEwASQBLAEcASQBMAEsARwBNAEgARwBLAE0ASABKAEYASABNAEoATgBPAFAATgBRAE8AUgBTAFQAUgBVAFMATgBUAFEATgBSAFQAUQBTAE8AUQBUAFMATwBVAFAATwBTAFUAUABSAE4AUABVAFIAVgBXAFgAVgBZAFcAWgBbAFwAWgBdAFsAVgBcAFkAVgBaAFwAWQBbAFcAWQBcAFsAVwBdAFgAVwBbAF0AWABaAFYAWABdAFoAXgBfAGAAXgBhAF8AYgBjAGQAYgBlAGMAXgBkAGEAXgBiAGQAYQBjAF8AYQBkAGMAXwBlAGAAXwBjAGUAYABiAF4AYABlAGIAZgBnAGgAZgBpAGcAagBrAGwAagBtAGsAZgBsAGkAZgBqAGwAaQBrAGcAaQBsAGsAZwBtAGgAZwBrAG0AaABqAGYAaABtAGoAbgBvAHAAbgBxAG8AcgBzAHQAcgB1AHMAbgB0AHEAbgByAHQAcQBzAG8AcQB0AHMAbwB1AHAAbwBzAHUAcAByAG4AcAB1AHIAdgB3AHgAdgB5AHcAegB7AHwAegB9AHsAdgB8AHkAdgB6AHwAeQB7AHcAeQB8AHsAdwB9AHgAdwB7AH0AeAB6AHYAeAB9AHoAfgB/AIAAfgCBAH8AggCDAIQAggCFAIMAfgCEAIEAfgCCAIQAgQCDAH8AgQCEAIMAfwCFAIAAfwCDAIUAgACCAH4AgACFAIIAhgCHAIgAhgCJAIcAigCLAIwAigCNAIsAhgCMAIkAhgCKAIwAiQCLAIcAiQCMAIsAhwCNAIgAhwCLAI0AiACKAIYAiACNAIoAjgCPAJAAjgCRAI8AkgCTAJQAkgCVAJMAjgCUAJEAjgCSAJQAkQCTAI8AkQCUAJMAjwCVAJAAjwCTAJUAkACSAI4AkACVAJIAlgCXAJgAlgCZAJcAmgCbAJwAmgCdAJsAlgCcAJkAlgCaAJwAmQCbAJcAmQCcAJsAlwCdAJgAlwCbAJ0AmACaAJYAmACdAJoAngCfAKAAngChAJ8AogCjAKQAogClAKMAngCkAKEAngCiAKQAoQCjAJ8AoQCkAKMAnwClAKAAnwCjAKUAoACiAJ4AoAClAKIApgCnAKgApgCpAKcAqgCrAKwAqgCtAKsApgCsAKkApgCqAKwAqQCrAKcAqQCsAKsApwCtAKgApwCrAK0AqACqAKYAqACtAKoArgCvALAArgCxAK8AsgCzALQAsgC1ALMArgC0ALEArgCyALQAsQCzAK8AsQC0ALMArwC1ALAArwCzALUAsACyAK4AsAC1ALIAtgC3ALgAtgC5ALcAugC7ALwAugC9ALsAtgC8ALkAtgC6ALwAuQC7ALcAuQC8ALsAtwC9ALgAtwC7AL0AuAC6ALYAuAC9ALoAvgC/AMAAvgDBAL8AwgDDAMQAwgDFAMMAvgDEAMEAvgDCAMQAwQDDAL8AwQDEAMMAvwDFAMAAvwDDAMUAwADCAL4AwADFAMIAxgDHAMgAxgDJAMcAygDLAMwAygDNAMsAxgDMAMkAxgDKAMwAyQDLAMcAyQDMAMsAxwDNAMgAxwDLAM0AyADKAMYAyADNAMoA";

function bytes(s: string): Uint16Array {
  const bin = atob(s), n = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) n[i] = bin.charCodeAt(i);
  return new Uint16Array(n.buffer);
}

const packed = bytes(PACKED);
export const POSITION = new Float32Array(packed.length);
for (let i = 0; i < packed.length; i += 3) {
  for (let c = 0; c < 3; c++) POSITION[i + c] = BOX.lo[c] + (packed[i + c] / 65535) * (BOX.hi[c] - BOX.lo[c]);
}
export const INDICES = bytes(INDEX);
