/**
 * Every door hotspot in the ship and the doorway it opens — GENERATED, do not edit.
 *
 * Regenerate with `npx tsx taoot/tools/doorways.ts`, which explains where a
 * hotspot lives and why the conditions travel with it. What it is FOR is in
 * `taoot/src/freeroam/doors.ts`.
 */

/** a comparison of one script global against a literal */
export interface DoorCond {
  var: string;
  op: "=" | "!=" | "<" | "<=" | ">" | ">=";
  value: string | number | boolean;
}

/** one room an `uparrow` from a hotspot's view can reach, and when */
export interface Lead {
  to: string;
  /** the standpoint in it the script's own `gotospecial` names */
  scene: string;
  view: string;
  /** the alternative condition-sets it is reachable under; `[]` = always */
  when: DoorCond[][];
}

/** one doorway this hotspot can stand the `door` prop up in */
export interface Doorway {
  /** the argument `setupprop` is called with */
  id: string;
  /**
   * The alternative condition-sets this doorway is called under in the
   * hotspot's own script — one entry per arm, every comparison in an arm
   * holding together. Empty means the script reaches it unconditionally.
   */
  when: DoorCond[][];
}

/** one door hotspot, in the view it is drawn in */
export interface DoorSpot {
  set: string;
  scene: string;
  view: string;
  /** the hotspot's own name — `door`, `locked`, `knock` and their variants */
  paint: string;
  /**
   * 0 when both CDs carry this hotspot and agree about it, else the CD this row
   * was read from — which also covers a hotspot only one CD has at all.
   */
  disc: 0 | 1 | 2;
  /**
   * The rooms an `uparrow` from this view can reach, and under what.
   *
   * Empty for a door that opens onto no room at all: `clarisdoor` on D deck,
   * Penny's on F and Shay's below are doorways a character stands in, and D-19
   * is not a place the game has. A lead whose conditions cannot hold is the
   * other way a door leads nowhere — the 1st Class Lounge's step is refused
   * outright in a tour, above the door rather than by it.
   */
  leads: Lead[];
  doorways: Doorway[];
}

export const DOOR_SPOTS: readonly DoorSpot[] = [
  { set: "a14", scene: "scene2", view: "view21", paint: "door", disc: 2,
    leads: [{ to: "halla", scene: "scene51", view: "view58", when: [] }],
    doorways: [{ id: "a14-halla", when: [] }] },
  { set: "b59", scene: "scene14", view: "view18", paint: "door", disc: 2,
    leads: [{ to: "hallb", scene: "scene29", view: "view41", when: [] }],
    doorways: [{ id: "b59-hallb", when: [] }] },
  { set: "b70", scene: "scene14", view: "view18", paint: "door", disc: 2,
    leads: [{ to: "hallb", scene: "scene31", view: "view49", when: [] }],
    doorways: [{ id: "b70-hallb", when: [] }] },
  { set: "bedsit1", scene: "scene3", view: "view21", paint: "door", disc: 1,
    leads: [],
    doorways: [{ id: "bedsitdoor", when: [] }] },
  { set: "bind", scene: "scene10", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "cargo", scene: "scene5", view: "view17", when: [[{"var":"savedeck","op":"=","value":"left"}]] }, { to: "cargo", scene: "scene5", view: "view16", when: [[{"var":"savedeck","op":"!=","value":"left"}]] }],
    doorways: [{ id: "bind-cargo", when: [] }] },
  { set: "bing", scene: "scene1", view: "view39", paint: "door", disc: 2,
    leads: [{ to: "cargo", scene: "scene5", view: "view17", when: [[{"var":"savedeck","op":"=","value":"left"}]] }, { to: "cargo", scene: "scene5", view: "view16", when: [[{"var":"savedeck","op":"!=","value":"left"}]] }],
    doorways: [{ id: "bing-cargo", when: [] }] },
  { set: "binl", scene: "scene10", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "cargo", scene: "scene5", view: "view17", when: [[{"var":"savedeck","op":"=","value":"left"}]] }, { to: "cargo", scene: "scene5", view: "view16", when: [[{"var":"savedeck","op":"!=","value":"left"}]] }],
    doorways: [{ id: "binl-cargo", when: [] }] },
  { set: "boil", scene: "scene40", view: "view44", paint: "door", disc: 2,
    leads: [{ to: "cargo", scene: "scene78", view: "view100", when: [[{"var":"savedeck","op":"=","value":"boil5"}]] }, { to: "boil", scene: "scene40", view: "view45", when: [[{"var":"savedeck","op":"=","value":"boil4"}],[{"var":"savedeck","op":"=","value":"boil3"}],[{"var":"savedeck","op":"=","value":"boil2"}],[{"var":"savedeck","op":"=","value":"boil1"}]] }],
    doorways: [{ id: "boil-boil", when: [] }] },
  { set: "boil", scene: "scene41", view: "view47", paint: "door", disc: 2,
    leads: [{ to: "boil", scene: "scene41", view: "view46", when: [[{"var":"savedeck","op":"=","value":"boil5"}],[{"var":"savedeck","op":"=","value":"boil4"}],[{"var":"savedeck","op":"=","value":"boil3"}],[{"var":"savedeck","op":"=","value":"boil2"}]] }, { to: "engine", scene: "scene38", view: "view71", when: [[{"var":"savedeck","op":"=","value":"boil1"}]] }],
    doorways: [{ id: "boil-engine", when: [] }] },
  { set: "c59", scene: "scene11", view: "view26", paint: "door", disc: 1,
    leads: [{ to: "hallc", scene: "scene31", view: "view49", when: [] }],
    doorways: [{ id: "c59-hallc", when: [] }] },
  { set: "c73", scene: "scene49", view: "view55", paint: "door", disc: 0,
    leads: [{ to: "hallc", scene: "scene27", view: "view35", when: [] }],
    doorways: [{ id: "c73-hallc", when: [] }] },
  { set: "c78", scene: "scene14", view: "view18", paint: "door", disc: 2,
    leads: [{ to: "hallc", scene: "scene31", view: "view49", when: [] }],
    doorways: [{ id: "c78-hallc d", when: [[{"var":"whitelight","op":"=","value":"off"}]] }, { id: "c78-hallc l", when: [[{"var":"whitelight","op":"!=","value":"off"}]] }] },
  { set: "cafe", scene: "scene35", view: "view74", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene37", view: "view41", when: [] }],
    doorways: [{ id: "cafe-str1c1", when: [] }] },
  { set: "carghall", scene: "scene21", view: "view20", paint: "door", disc: 2,
    leads: [{ to: "cargo", scene: "scene78", view: "view100", when: [] }],
    doorways: [{ id: "carghall-cargo", when: [] }] },
  { set: "cargo", scene: "scene5", view: "view16", paint: "door", disc: 2,
    leads: [{ to: "bing", scene: "scene1", view: "view38", when: [[{"var":"hallside","op":"=","value":"port"}]] }, { to: "binl", scene: "scene10", view: "view15", when: [[{"var":"hallside","op":"!=","value":"port"},{"var":"carlights","op":"!=","value":false}]] }, { to: "bind", scene: "scene10", view: "view15", when: [[{"var":"hallside","op":"!=","value":"port"},{"var":"carlights","op":"=","value":false}]] }],
    doorways: [{ id: "cargo-bin", when: [] }] },
  { set: "cargo", scene: "scene5", view: "view17", paint: "door", disc: 2,
    leads: [{ to: "bing", scene: "scene1", view: "view38", when: [[{"var":"hallside","op":"=","value":"port"}],[{"var":"hallside","op":"!=","value":"port"}]] }],
    doorways: [{ id: "cargo-bincar", when: [] }] },
  { set: "cargo", scene: "scene6", view: "view26", paint: "door", disc: 2,
    leads: [],
    doorways: [{ id: "cargo-bincar", when: [] }] },
  { set: "cargo", scene: "scene6", view: "view27", paint: "door", disc: 2,
    leads: [],
    doorways: [{ id: "cargo-bin", when: [[{"var":"hallside","op":"=","value":"star"}]] }] },
  { set: "cargo", scene: "scene78", view: "view101", paint: "door", disc: 2,
    leads: [{ to: "carghall", scene: "scene21", view: "view21", when: [[{"var":"hallside","op":"=","value":"port"}]] }, { to: "boil", scene: "scene40", view: "view45", when: [[{"var":"hallside","op":"!=","value":"port"},{"var":"hallside","op":"=","value":"star"}]] }],
    doorways: [{ id: "cargo-boil", when: [] }] },
  { set: "control", scene: "scene10", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "turb", scene: "scene63", view: "view75", when: [] }],
    doorways: [{ id: "control-turb", when: [] }] },
  { set: "control", scene: "scene12", view: "view32", paint: "door", disc: 2,
    leads: [{ to: "engine", scene: "scene36", view: "view66", when: [] }],
    doorways: [{ id: "control-engine", when: [] }] },
  { set: "crew", scene: "scene10", view: "view17", paint: "door", disc: 2,
    leads: [{ to: "fore", scene: "scene593", view: "view595", when: [] }],
    doorways: [{ id: "crew-fore", when: [] }] },
  { set: "crew", scene: "scene11", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "carghall", scene: "scene20", view: "view12", when: [] }],
    doorways: [{ id: "crew-carghall", when: [] }] },
  { set: "decka", scene: "scene354", view: "view425", paint: "door", disc: 2,
    leads: [{ to: "gstair2", scene: "scene14", view: "view37", when: [] }],
    doorways: [{ id: "decka-gs2 s", when: [] }] },
  { set: "decka", scene: "scene355", view: "view432", paint: "door", disc: 2,
    leads: [{ to: "gstair2", scene: "scene16", view: "view44", when: [] }],
    doorways: [{ id: "decka-gs2 p", when: [] }] },
  { set: "decka", scene: "scene356", view: "view394", paint: "door", disc: 2,
    leads: [{ to: "stair1c1", scene: "scene57", view: "view59", when: [] }],
    doorways: [{ id: "decka-str1c1 p", when: [] }] },
  { set: "decka", scene: "scene357", view: "view403", paint: "door", disc: 2,
    leads: [{ to: "stair1c1", scene: "scene58", view: "view76", when: [] }],
    doorways: [{ id: "decka-str1c1 s", when: [] }] },
  { set: "deckbd", scene: "scene322", view: "view327", paint: "door", disc: 2,
    leads: [{ to: "vestport", scene: "scene17", view: "view20", when: [] }],
    doorways: [{ id: "deckbd-vestport", when: [] }] },
  { set: "deckbd", scene: "scene35", view: "view102", paint: "door", disc: 2,
    leads: [{ to: "wireless", scene: "scene10", view: "view14", when: [] }],
    doorways: [{ id: "deckbd-wireless", when: [] }] },
  { set: "deckbd", scene: "scene36", view: "view111", paint: "door", disc: 2,
    leads: [{ to: "veststbd", scene: "scene17", view: "view19", when: [] }],
    doorways: [{ id: "deckbd-veststar", when: [] }] },
  { set: "deckbd", scene: "scene36", view: "view115", paint: "door", disc: 2,
    leads: [{ to: "gym", scene: "scene12", view: "view47", when: [] }],
    doorways: [{ id: "deckbd-gym", when: [] }] },
  { set: "deckbd", scene: "scene45", view: "view249", paint: "door", disc: 2,
    leads: [{ to: "stair2c", scene: "scene45", view: "view65", when: [] }],
    doorways: [{ id: "deckbd-str2c p", when: [] }] },
  { set: "deckbd", scene: "scene47", view: "view266", paint: "door", disc: 2,
    leads: [{ to: "stair2c", scene: "scene45", view: "view64", when: [] }],
    doorways: [{ id: "deckbd-str2c s", when: [] }] },
  { set: "deckbd2", scene: "scene322", view: "view327", paint: "door", disc: 1,
    leads: [{ to: "vestport", scene: "scene17", view: "view20", when: [] }],
    doorways: [{ id: "deckbd2-vestpor", when: [] }] },
  { set: "deckbd2", scene: "scene35", view: "view102", paint: "door", disc: 1,
    leads: [{ to: "wireless", scene: "scene10", view: "view14", when: [] }],
    doorways: [{ id: "deckbd2-wireles", when: [] }] },
  { set: "deckbd2", scene: "scene36", view: "view111", paint: "door", disc: 1,
    leads: [{ to: "veststbd", scene: "scene17", view: "view19", when: [] }],
    doorways: [{ id: "deckbd2-veststa", when: [] }] },
  { set: "deckbd2", scene: "scene36", view: "view115", paint: "door", disc: 1,
    leads: [{ to: "gym", scene: "scene12", view: "view47", when: [] }],
    doorways: [{ id: "deckbd2-gym", when: [] }] },
  { set: "deckbd2", scene: "scene45", view: "view249", paint: "door", disc: 1,
    leads: [{ to: "stair2c", scene: "scene45", view: "view65", when: [] }],
    doorways: [{ id: "deckbd2-str2c p", when: [] }] },
  { set: "deckbd2", scene: "scene47", view: "view266", paint: "door", disc: 1,
    leads: [{ to: "stair2c", scene: "scene45", view: "view64", when: [] }],
    doorways: [{ id: "deckbd2-str2c s", when: [] }] },
  { set: "ebath", scene: "scene10", view: "view18", paint: "door", disc: 2,
    leads: [{ to: "ehall", scene: "scene12", view: "view23", when: [] }],
    doorways: [{ id: "ebath-ehall", when: [] }] },
  { set: "ehall", scene: "scene12", view: "view24", paint: "door", disc: 2,
    leads: [{ to: "ebath", scene: "scene10", view: "view19", when: [] }],
    doorways: [{ id: "ehall-ebath", when: [] }] },
  { set: "ehall", scene: "turkdoor", view: "exit", paint: "door", disc: 2,
    leads: [{ to: "turk", scene: "scene109", view: "view121", when: [] }],
    doorways: [{ id: "ehall-turk", when: [] }] },
  { set: "engine", scene: "scene127", view: "view135", paint: "door", disc: 2,
    leads: [{ to: "scot2", scene: "scene12", view: "view25", when: [] }],
    doorways: [{ id: "engine-scot2", when: [] }] },
  { set: "engine", scene: "scene36", view: "view67", paint: "door", disc: 2,
    leads: [{ to: "control", scene: "scene12", view: "view31", when: [] }],
    doorways: [{ id: "engine-control", when: [] }] },
  { set: "engine", scene: "scene38", view: "view70", paint: "door", disc: 2,
    leads: [{ to: "boil", scene: "scene41", view: "view46", when: [] }],
    doorways: [{ id: "engine-boil", when: [] }] },
  { set: "fore", scene: "scene593", view: "view594", paint: "door", disc: 2,
    leads: [{ to: "crew", scene: "scene10", view: "view16", when: [] }],
    doorways: [{ id: "fore-crew", when: [] }] },
  { set: "gstair1", scene: "scene18", view: "view44", paint: "door", disc: 0,
    leads: [{ to: "vestport", scene: "scene17", view: "view19", when: [] }],
    doorways: [{ id: "gs1-vestport", when: [] }] },
  { set: "gstair1", scene: "scene19", view: "view43", paint: "door", disc: 0,
    leads: [{ to: "veststbd", scene: "scene17", view: "view18", when: [] }],
    doorways: [{ id: "gs1-veststar", when: [] }] },
  { set: "gstair2", scene: "scene11", view: "view22", paint: "door", disc: 0,
    leads: [{ to: "halla", scene: "scene72", view: "view95", when: [] }],
    doorways: [{ id: "gs2-halla p", when: [] }] },
  { set: "gstair2", scene: "scene12", view: "view26", paint: "door", disc: 0,
    leads: [{ to: "halla", scene: "scene20", view: "view26", when: [] }],
    doorways: [{ id: "gs2-halla s", when: [] }] },
  { set: "gstair2", scene: "scene14", view: "view35", paint: "door", disc: 0,
    leads: [{ to: "lnghall", scene: "scene11", view: "view16", when: [] }],
    doorways: [{ id: "gs2-lnghall", when: [] }] },
  { set: "gstair2", scene: "scene14", view: "view36", paint: "door", disc: 0,
    leads: [{ to: "decka", scene: "scene354", view: "view424", when: [] }],
    doorways: [{ id: "gs2-decka s", when: [] }] },
  { set: "gstair2", scene: "scene16", view: "view45", paint: "door", disc: 0,
    leads: [{ to: "decka", scene: "scene355", view: "view433", when: [] }],
    doorways: [{ id: "gs2-decka p", when: [] }] },
  { set: "gstair3", scene: "scene14", view: "view35", paint: "door", disc: 0,
    leads: [{ to: "hallb", scene: "scene53", view: "view56", when: [[{"var":"savedeck","op":"=","value":"b"}]] }, { to: "hallc", scene: "scene53", view: "view56", when: [[{"var":"savedeck","op":"=","value":"c"}]] }],
    doorways: [{ id: "gs3-hallc s", when: [[{"var":"savedeck","op":"=","value":"b"}],[{"var":"savedeck","op":"=","value":"c"}]] }] },
  { set: "gstair3", scene: "scene14", view: "view36", paint: "door", disc: 0,
    leads: [],
    doorways: [{ id: "gs3-purs", when: [[{"var":"savedeck","op":"=","value":"c"},{"var":"tour","op":"=","value":false},{"var":"mission","op":"<","value":4}]] }] },
  { set: "gstair3", scene: "scene16", view: "view43", paint: "door", disc: 0,
    leads: [{ to: "hallb", scene: "scene12", view: "view21", when: [[{"var":"savedeck","op":"=","value":"b"}]] }, { to: "hallc", scene: "scene12", view: "view21", when: [[{"var":"savedeck","op":"=","value":"c"}]] }],
    doorways: [{ id: "gs3-hallc p", when: [[{"var":"savedeck","op":"=","value":"b"}],[{"var":"savedeck","op":"=","value":"c"}]] }] },
  { set: "gym", scene: "scene12", view: "view45", paint: "door", disc: 0,
    leads: [{ to: "veststbd", scene: "scene17", view: "view20", when: [] }],
    doorways: [{ id: "gym-veststar", when: [] }] },
  { set: "gym", scene: "scene12", view: "view46", paint: "door", disc: 0,
    leads: [{ to: "deckbd", scene: "scene36", view: "view114", when: [] }, { to: "deckbd2", scene: "scene36", view: "view114", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "gym-deckbd", when: [] }] },
  { set: "halla", scene: "scene20", view: "view25", paint: "door", disc: 0,
    leads: [{ to: "gstair2", scene: "scene12", view: "view27", when: [] }],
    doorways: [{ id: "halla-gstair2 s", when: [[{"var":"hallside","op":"=","value":"star"}]] }] },
  { set: "halla", scene: "scene51", view: "view57", paint: "door", disc: 0,
    leads: [{ to: "a14", scene: "scene2", view: "view20", when: [] }],
    doorways: [{ id: "sashadoor", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"mission","op":"=","value":1},{"var":"phase","op":"=","value":3}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"neckphase","op":"!=","value":7},{"var":"neckphase","op":"!=","value":8},{"var":"neckphase","op":"=","value":6}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"neckphase","op":"!=","value":7},{"var":"neckphase","op":"!=","value":8},{"var":"neckphase","op":"!=","value":6},{"var":"neckphase","op":"!=","value":9},{"var":"mission","op":"=","value":4}]] }] },
  { set: "halla", scene: "scene72", view: "view96", paint: "door", disc: 0,
    leads: [{ to: "gstair2", scene: "scene11", view: "view23", when: [] }],
    doorways: [{ id: "halla-gstair2 p", when: [[{"var":"hallside","op":"!=","value":"star"},{"var":"hallside","op":"=","value":"port"}]] }] },
  { set: "hallb", scene: "scene12", view: "view22", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene108", view: "view110", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { to: "gstair3", scene: "scene16", view: "view42", when: [[{"var":"hallside","op":"!=","value":"star"}]] }],
    doorways: [{ id: "hallb-str1c1 s", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { id: "hallb-gstair3 p", when: [[{"var":"hallside","op":"!=","value":"star"},{"var":"hallside","op":"=","value":"port"}]] }] },
  { set: "hallb", scene: "scene29", view: "view40", paint: "door", disc: 0,
    leads: [{ to: "b59", scene: "scene14", view: "view19", when: [] }],
    doorways: [{ id: "hallb-b59", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"star"}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"star"},{"var":"letterphase","op":"!=","value":2},{"var":"letterphase","op":"!=","value":3},{"var":"letterphase","op":"=","value":4}]] }] },
  { set: "hallb", scene: "scene31", view: "view48", paint: "door", disc: 0,
    leads: [{ to: "b70", scene: "scene14", view: "view19", when: [] }],
    doorways: [{ id: "hallb-b70", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"neckphase","op":"=","value":2}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"neckphase","op":"=","value":5}]] }] },
  { set: "hallb", scene: "scene53", view: "view57", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene101", view: "view102", when: [[{"var":"hallside","op":"=","value":"port"}]] }, { to: "gstair3", scene: "scene14", view: "view34", when: [[{"var":"hallside","op":"!=","value":"port"}]] }],
    doorways: [{ id: "hallb-gstair3 s", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { id: "hallb-str1c1 p", when: [[{"var":"hallside","op":"!=","value":"star"},{"var":"hallside","op":"=","value":"port"}]] }] },
  { set: "hallc", scene: "scene12", view: "view22", paint: "door", disc: 0,
    leads: [{ to: "stair1c2", scene: "scene129", view: "view138", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { to: "gstair3", scene: "scene16", view: "view42", when: [[{"var":"hallside","op":"!=","value":"star"}]] }],
    doorways: [{ id: "hallc-str1c2 s", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { id: "hallc-gstair3 p", when: [[{"var":"hallside","op":"!=","value":"star"},{"var":"hallside","op":"=","value":"port"}]] }] },
  { set: "hallc", scene: "scene27", view: "view34", paint: "door", disc: 0,
    leads: [{ to: "c73", scene: "scene49", view: "view54", when: [] }],
    doorways: [{ id: "hallc-c73", when: [[{"var":"hallside","op":"=","value":"star"}]] }] },
  { set: "hallc", scene: "scene31", view: "view48", paint: "door", disc: 1,
    leads: [{ to: "c59", scene: "scene11", view: "view25", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { to: "c78", scene: "scene14", view: "view19", when: [[{"var":"hallside","op":"!=","value":"star"}]] }],
    doorways: [{ id: "hallc-c59", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"star"},{"var":"mission","op":"=","value":4}]] }, { id: "hallc-c78", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"mission","op":"<","value":4},{"var":"joneshint","op":"=","value":1}]] }] },
  { set: "hallc", scene: "scene31", view: "view48", paint: "door", disc: 2,
    leads: [{ to: "c59", scene: "scene11", view: "view25", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { to: "c78", scene: "scene14", view: "view19", when: [[{"var":"hallside","op":"!=","value":"star"}]] }],
    doorways: [{ id: "hallc-c59", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"star"},{"var":"mission","op":"=","value":4}]] }, { id: "hallc-c78", when: [[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"mission","op":"<","value":4},{"var":"joneshint","op":"=","value":1},{"var":"burnsphase","op":"!=","value":"left"}],[{"var":"tour","op":"=","value":false},{"var":"hallside","op":"=","value":"port"},{"var":"mission","op":"<","value":4},{"var":"joneshint","op":"=","value":1}]] }] },
  { set: "hallc", scene: "scene53", view: "view57", paint: "door", disc: 0,
    leads: [{ to: "stair1c2", scene: "scene130", view: "view132", when: [[{"var":"hallside","op":"=","value":"port"}]] }, { to: "gstair3", scene: "scene14", view: "view34", when: [[{"var":"hallside","op":"!=","value":"port"}]] }],
    doorways: [{ id: "hallc-gstair3 s", when: [[{"var":"hallside","op":"=","value":"star"}]] }, { id: "hallc-str1c2 p", when: [[{"var":"hallside","op":"!=","value":"star"},{"var":"hallside","op":"=","value":"port"}]] }] },
  { set: "halld", scene: "scene21", view: "view32", paint: "door", disc: 2,
    leads: [{ to: "recept1c", scene: "scene90", view: "view96", when: [] }],
    doorways: [{ id: "halld-recept1c", when: [] }] },
  { set: "halld", scene: "scene69", view: "view79", paint: "knock", disc: 2,
    leads: [],
    doorways: [{ id: "clarisdoor", when: [[{"var":"tour","op":"=","value":false},{"var":"tour","op":"=","value":false},{"var":"mission","op":"=","value":2},{"var":"phase","op":"=","value":3}],[{"var":"tour","op":"=","value":false},{"var":"tour","op":"=","value":false},{"var":"mission","op":"=","value":2},{"var":"phase","op":"=","value":2}],[{"var":"tour","op":"=","value":false},{"var":"tour","op":"=","value":false}]] }] },
  { set: "halld", scene: "scene99", view: "view103", paint: "door", disc: 2,
    leads: [{ to: "sqhall", scene: "scene10", view: "view17", when: [] }],
    doorways: [{ id: "halld-sqhall", when: [] }] },
  { set: "hallf2c", scene: "scene10", view: "view13", paint: "door", disc: 0,
    leads: [{ to: "turb", scene: "scene82", view: "view89", when: [] }],
    doorways: [{ id: "hallf2c-turb", when: [] }] },
  { set: "hallf2c", scene: "scene59", view: "view76", paint: "knock", disc: 2,
    leads: [],
    doorways: [{ id: "pennydoor", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":"<","value":4}]] }] },
  { set: "hallf2c", scene: "scene60", view: "view69", paint: "door", disc: 0,
    leads: [{ to: "stair2c", scene: "scene13", view: "view29", when: [] }],
    doorways: [{ id: "hallf2c-stair2c", when: [] }] },
  { set: "hallf3c", scene: "scene11", view: "view15", paint: "knock", disc: 2,
    leads: [],
    doorways: [{ id: "shaydoor", when: [[{"var":"tour","op":"=","value":false},{"var":"letterphase","op":"=","value":4}],[{"var":"tour","op":"=","value":false},{"var":"letterphase","op":"!=","value":4},{"var":"letterphase","op":"=","value":5}]] }] },
  { set: "lnghall", scene: "scene10", view: "view12", paint: "door", disc: 0,
    leads: [{ to: "lounge1c", scene: "scene10", view: "view16", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4},{"var":"savedeck","op":"=","value":"stair1c1"}]] }, { to: "lounge1c", scene: "scene14", view: "view37", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4},{"var":"savedeck","op":"=","value":"gstair2"}]] }],
    doorways: [{ id: "lnghall-lounge", when: [] }] },
  { set: "lnghall", scene: "scene11", view: "view17", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene57", view: "view62", when: [[{"var":"savedeck","op":"=","value":"stair1c1"}]] }, { to: "gstair2", scene: "scene14", view: "view34", when: [[{"var":"savedeck","op":"=","value":"gstair2"}]] }],
    doorways: [{ id: "lnghall-gstair2", when: [] }] },
  { set: "lounge1c", scene: "scene10", view: "view17", paint: "door", disc: 1,
    leads: [{ to: "lnghall", scene: "scene10", view: "view13", when: [] }],
    doorways: [{ id: "lng-lnghall a", when: [] }] },
  { set: "lounge1c", scene: "scene14", view: "view36", paint: "door", disc: 1,
    leads: [{ to: "lnghall", scene: "scene10", view: "view13", when: [] }],
    doorways: [{ id: "lng-lnghall f", when: [] }] },
  { set: "poop", scene: "scene482", view: "view566", paint: "door", disc: 2,
    leads: [{ to: "stair2c", scene: "scene41", view: "view49", when: [] }],
    doorways: [{ id: "poop-str2c p", when: [] }] },
  { set: "poop", scene: "scene484", view: "view557", paint: "door", disc: 2,
    leads: [{ to: "stair2c", scene: "scene42", view: "view52", when: [] }],
    doorways: [{ id: "poop-str2c s", when: [] }] },
  { set: "recept1c", scene: "scene13", view: "view31", paint: "door", disc: 2,
    leads: [{ to: "turkstrs", scene: "scene30", view: "view42", when: [] }],
    doorways: [{ id: "r1c-turkstrs p", when: [] }] },
  { set: "recept1c", scene: "scene37", view: "view41", paint: "door", disc: 2,
    leads: [{ to: "turkstrs", scene: "scene30", view: "view41", when: [] }],
    doorways: [{ id: "r1c-turkstrs s", when: [] }] },
  { set: "recept1c", scene: "scene90", view: "view91", paint: "door", disc: 2,
    leads: [{ to: "halld", scene: "scene21", view: "view31", when: [] }],
    doorways: [{ id: "recept-ddeck", when: [] }] },
  { set: "scot1", scene: "scene23", view: "view44", paint: "door", disc: 2,
    leads: [{ to: "turkstrs", scene: "scene12", view: "view24", when: [] }],
    doorways: [{ id: "scot1-turkstrs", when: [] }] },
  { set: "scot1", scene: "scene27", view: "view59", paint: "door", disc: 2,
    leads: [{ to: "scot2", scene: "scene10", view: "view15", when: [] }],
    doorways: [{ id: "scot1-scot2", when: [] }] },
  { set: "scot2", scene: "scene10", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "scot1", scene: "scene27", view: "view58", when: [] }],
    doorways: [{ id: "scot2-scot1", when: [] }] },
  { set: "scot2", scene: "scene11", view: "view29", paint: "door", disc: 2,
    leads: [{ to: "scot3", scene: "scene10", view: "view15", when: [] }],
    doorways: [{ id: "scot2-scot3", when: [] }] },
  { set: "scot3", scene: "scene10", view: "view14", paint: "door", disc: 2,
    leads: [{ to: "scot2", scene: "scene11", view: "view28", when: [] }],
    doorways: [{ id: "scot3-scot2", when: [] }] },
  { set: "scot3", scene: "scene12", view: "view28", paint: "door", disc: 2,
    leads: [{ to: "stair2c", scene: "scene41", view: "view49", when: [] }],
    doorways: [{ id: "scot3-stair2c", when: [] }] },
  { set: "smoke", scene: "scene10", view: "view32", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene56", view: "view93", when: [] }],
    doorways: [{ id: "smoke-str1c1 p", when: [] }] },
  { set: "smoke", scene: "scene14", view: "view16", paint: "door", disc: 0,
    leads: [{ to: "stair1c1", scene: "scene55", view: "view90", when: [] }],
    doorways: [{ id: "smoke-str1c1 s", when: [] }] },
  { set: "sqhall", scene: "scene10", view: "view16", paint: "door", disc: 2,
    leads: [{ to: "halld", scene: "scene99", view: "view102", when: [] }],
    doorways: [{ id: "sqhall-halld", when: [] }] },
  { set: "sqhall", scene: "scene33", view: "view42", paint: "door", disc: 2,
    leads: [{ to: "squash", scene: "scene15", view: "view16", when: [] }],
    doorways: [{ id: "sqhall-squash", when: [] }] },
  { set: "squash", scene: "scene15", view: "view17", paint: "door", disc: 2,
    leads: [{ to: "sqhall", scene: "scene33", view: "view41", when: [] }],
    doorways: [{ id: "squash-sqhall", when: [] }] },
  { set: "stair1c1", scene: "scene101", view: "view103", paint: "door", disc: 0,
    leads: [{ to: "hallb", scene: "scene53", view: "view56", when: [] }],
    doorways: [{ id: "str1c1-hallb p", when: [] }] },
  { set: "stair1c1", scene: "scene108", view: "view109", paint: "door", disc: 0,
    leads: [{ to: "hallb", scene: "scene12", view: "view21", when: [] }],
    doorways: [{ id: "str1c1-hallb s", when: [] }] },
  { set: "stair1c1", scene: "scene37", view: "view40", paint: "door", disc: 0,
    leads: [{ to: "cafe", scene: "scene35", view: "view59", when: [] }],
    doorways: [{ id: "str1c1-cafe", when: [] }] },
  { set: "stair1c1", scene: "scene55", view: "view89", paint: "door", disc: 0,
    leads: [{ to: "smoke", scene: "scene14", view: "view17", when: [] }],
    doorways: [{ id: "str1c1-smoke s", when: [] }] },
  { set: "stair1c1", scene: "scene56", view: "view94", paint: "door", disc: 0,
    leads: [{ to: "smoke", scene: "scene10", view: "view33", when: [] }],
    doorways: [{ id: "str1c1-smoke p", when: [] }] },
  { set: "stair1c1", scene: "scene57", view: "view60", paint: "door", disc: 0,
    leads: [{ to: "decka", scene: "scene356", view: "view395", when: [] }],
    doorways: [{ id: "str1c1-decka p", when: [] }] },
  { set: "stair1c1", scene: "scene57", view: "view61", paint: "door", disc: 0,
    leads: [{ to: "lnghall", scene: "scene11", view: "view16", when: [] }],
    doorways: [{ id: "str1c1-lnghall", when: [] }] },
  { set: "stair1c1", scene: "scene58", view: "view75", paint: "door", disc: 0,
    leads: [{ to: "decka", scene: "scene357", view: "view402", when: [] }],
    doorways: [{ id: "str1c1-decka s", when: [] }] },
  { set: "stair1c2", scene: "scene129", view: "view137", paint: "door", disc: 0,
    leads: [{ to: "hallc", scene: "scene12", view: "view21", when: [] }],
    doorways: [{ id: "str1c2-hallc s", when: [] }] },
  { set: "stair1c2", scene: "scene130", view: "view131", paint: "door", disc: 0,
    leads: [{ to: "hallc", scene: "scene53", view: "view56", when: [] }],
    doorways: [{ id: "str1c2-hallc p", when: [] }] },
  { set: "stair2c", scene: "scene13", view: "view28", paint: "door", disc: 0,
    leads: [{ to: "hallf2c", scene: "scene60", view: "view70", when: [] }],
    doorways: [{ id: "str2c-hallf2c", when: [] }] },
  { set: "stair2c", scene: "scene41", view: "view48", paint: "door", disc: 0,
    leads: [{ to: "poop", scene: "scene482", view: "view567", when: [[{"var":"savedeck","op":"=","value":"b"}]] }, { to: "scot3", scene: "scene12", view: "view29", when: [[{"var":"savedeck","op":"!=","value":"b"},{"var":"savedeck","op":"=","value":"e"}]] }],
    doorways: [{ id: "str2c-poop p", when: [[{"var":"savedeck","op":"=","value":"b"}]] }, { id: "str2c-scot3", when: [[{"var":"savedeck","op":"=","value":"e"}]] }] },
  { set: "stair2c", scene: "scene42", view: "view53", paint: "door", disc: 0,
    leads: [{ to: "poop", scene: "scene484", view: "view556", when: [[{"var":"savedeck","op":"=","value":"b"}]] }],
    doorways: [{ id: "str2c-poop s", when: [[{"var":"savedeck","op":"=","value":"b"}]] }] },
  { set: "stair2c", scene: "scene45", view: "view64", paint: "door", disc: 0,
    leads: [{ to: "deckbd", scene: "scene45", view: "view250", when: [] }, { to: "deckbd2", scene: "scene45", view: "view250", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "str2c-deckbd p", when: [] }] },
  { set: "stair2c", scene: "scene45", view: "view65", paint: "door", disc: 0,
    leads: [{ to: "deckbd", scene: "scene47", view: "view265", when: [] }, { to: "deckbd2", scene: "scene47", view: "view265", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "str2c-deckbd s", when: [] }] },
  { set: "turb", scene: "scene63", view: "view74", paint: "door", disc: 0,
    leads: [{ to: "control", scene: "scene10", view: "view13", when: [] }],
    doorways: [{ id: "turb-control", when: [] }] },
  { set: "turb", scene: "scene82", view: "view90", paint: "door", disc: 0,
    leads: [{ to: "hallf2c", scene: "scene10", view: "view14", when: [] }],
    doorways: [{ id: "turb-hallf2c", when: [] }] },
  { set: "turk", scene: "scene109", view: "view120", paint: "door", disc: 2,
    leads: [{ to: "ehall", scene: "turkdoor", view: "enter", when: [] }],
    doorways: [{ id: "turk-ehall", when: [] }] },
  { set: "turk", scene: "scene11", view: "view115", paint: "door", disc: 2,
    leads: [{ to: "turkstrs", scene: "scene10", view: "view15", when: [] }],
    doorways: [{ id: "turk-turkstrs", when: [] }] },
  { set: "turkstrs", scene: "scene10", view: "view16", paint: "door", disc: 2,
    leads: [{ to: "turk", scene: "scene11", view: "view116", when: [] }],
    doorways: [{ id: "turkstrs-turk", when: [] }] },
  { set: "turkstrs", scene: "scene12", view: "view23", paint: "door", disc: 2,
    leads: [{ to: "scot1", scene: "scene23", view: "view45", when: [] }],
    doorways: [{ id: "turkstrs-scot1", when: [] }] },
  { set: "turkstrs", scene: "scene30", view: "view41", paint: "door", disc: 2,
    leads: [{ to: "recept1c", scene: "scene13", view: "view32", when: [] }],
    doorways: [{ id: "turkstrs-r1c p", when: [] }] },
  { set: "turkstrs", scene: "scene30", view: "view42", paint: "door", disc: 2,
    leads: [{ to: "recept1c", scene: "scene37", view: "view40", when: [] }],
    doorways: [{ id: "turkstrs-r1c s", when: [] }] },
  { set: "vestport", scene: "scene17", view: "view18", paint: "door", disc: 0,
    leads: [{ to: "gstair1", scene: "scene18", view: "view45", when: [] }],
    doorways: [{ id: "vestport-gs1", when: [] }] },
  { set: "vestport", scene: "scene17", view: "view21", paint: "door", disc: 1,
    leads: [{ to: "deckbd", scene: "scene213", view: "view317", when: [] }, { to: "deckbd2", scene: "scene322", view: "view328", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "vestport-deckbd", when: [] }] },
  { set: "vestport", scene: "scene17", view: "view21", paint: "door", disc: 2,
    leads: [{ to: "deckbd", scene: "scene322", view: "view328", when: [] }, { to: "deckbd2", scene: "scene322", view: "view328", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "vestport-deckbd", when: [] }] },
  { set: "veststbd", scene: "scene17", view: "view18", paint: "door", disc: 1,
    leads: [{ to: "deckbd", scene: "scene379", view: "view382", when: [] }, { to: "deckbd2", scene: "scene36", view: "view114", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "veststar-deckbd", when: [] }] },
  { set: "veststbd", scene: "scene17", view: "view18", paint: "door", disc: 2,
    leads: [{ to: "deckbd", scene: "scene36", view: "view110", when: [] }, { to: "deckbd2", scene: "scene36", view: "view110", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "veststar-deckbd", when: [] }] },
  { set: "veststbd", scene: "scene17", view: "view19", paint: "door", disc: 0,
    leads: [{ to: "gstair1", scene: "scene19", view: "view42", when: [] }],
    doorways: [{ id: "veststar-gs1", when: [] }] },
  { set: "veststbd", scene: "scene17", view: "view21", paint: "door", disc: 0,
    leads: [{ to: "gym", scene: "scene12", view: "view47", when: [] }],
    doorways: [{ id: "veststar-gym", when: [] }] },
  { set: "wireless", scene: "scene10", view: "view13", paint: "door", disc: 0,
    leads: [{ to: "deckbd", scene: "scene35", view: "view103", when: [] }, { to: "deckbd2", scene: "scene35", view: "view103", when: [[{"var":"tour","op":"=","value":false},{"var":"mission","op":">=","value":4}]] }],
    doorways: [{ id: "wireless-deckbd", when: [] }] },
];
