/**
 * Scan every script-bearing game file, find engine commands invoked by scripts
 * that have no real builtin (unregistered) or only a no-op/stub, and (re)write
 * builtins_todo.md.
 *
 *   npx tsx tools/scancmds.mts [repoRoot] [outFile]
 */
import { readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, basename } from "node:path";
import { readContainerFile } from "../src/df/container";
import { sniffScript, Token, OPCODES } from "../src/df/script";

const ROOT = process.argv[2] ?? ".";
const OUT = process.argv[3] ?? join(ROOT, "builtins_todo.md");
const GAMEFILES = join(ROOT, "gamefiles");
const BUILTINS = join(ROOT, "src", "engine", "builtins");
const INTERP = join(ROOT, "src", "engine", "interp.ts");

const SCRIPT_BEARING = /\.(SET|STG|PUP|SHP|CST|MOV)$/i;
const NOT_GAME_DATA = new Set(["install", "support", "shots", "sneak"]);
const isBoot = (n: string) => /^BOOTFILE$/i.test(n);
const band = (id: number) =>
  id >= 24000 ? "transition" : id >= 20000 ? "query/fn" : id >= 16000 ? "property" : id >= 12000 ? "action" : "other";
const opId = (name: string) => [...OPCODES].find(([, n]) => n === name)?.[0] ?? -1;

// ---- registered builtins (+ which are no-op/stub) ----
const registered = new Set<string>();
const noop = new Set<string>();
function collect(src: string) {
  for (const m of src.matchAll(/\br\(\s*"([a-zA-Z0-9_]+)"\s*,\s*([^\n]*)/g)) {
    registered.add(m[1]);
    if (/=>\s*(\{\s*\}|0|-?\d+)\s*\)\s*;\s*(\/\/.*)?$/.test(m[2])) noop.add(m[1]);
  }
  for (const m of src.matchAll(/registerSpecial\(\s*"([a-zA-Z0-9_]+)"/g)) registered.add(m[1]);
  for (const m of src.matchAll(/for \(const (\w+) of \[([\s\S]*?)\]\)\s*\{([\s\S]*?)\n\s*\}/g)) {
    const [, v, arr, body] = m;
    if (!new RegExp(`\\br\\(\\s*${v}\\b|registerSpecial\\(\\s*${v}\\b`).test(body)) continue;
    const isNoop = /=>\s*\{\s*\}|=>\s*0\b|=>\s*t\b|=>\s*\w+\s*\)/.test(body);
    for (const [, n] of arr.matchAll(/"([a-zA-Z0-9_]+)"/g)) {
      registered.add(n);
      if (isNoop) noop.add(n);
    }
  }
}
for (const f of readdirSync(BUILTINS)) collect(readFileSync(join(BUILTINS, f), "utf8"));
collect(readFileSync(INTERP, "utf8"));

// ---- commands used across the corpus ----
function* walk(dir: string): Generator<string> {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    // Skip the trees a CD rip carries that aren't the game's own data — chiefly
    // `sneak/`, a sneak-preview demo whose bootfile/menu scripts would otherwise
    // count as commands the shipped game invokes.
    if (statSync(p).isDirectory()) { if (!NOT_GAME_DATA.has(e.toLowerCase())) yield* walk(p); }
    else yield p;
  }
}
const usedFiles = new Map<string, Set<string>>();
const usedCount = new Map<string, number>();
const usedExt = new Map<string, Set<string>>();
let filesScanned = 0;
for (const path of walk(GAMEFILES)) {
  const name = basename(path);
  if (!SCRIPT_BEARING.test(name) && !isBoot(name)) continue;
  let cf;
  try {
    cf = readContainerFile(new Uint8Array(readFileSync(path)));
  } catch {
    continue;
  }
  filesScanned++;
  const ext = isBoot(name) ? "BOOTFILE" : name.slice(name.lastIndexOf(".") + 1).toUpperCase();
  for (const c of cf.containers) {
    const tokens = sniffScript(c.data);
    if (!tokens) continue;
    for (const op of tokens.filter((t): t is Token & { kind: "op" } => t.kind === "op")) {
      if (op.id < 12000) continue;
      if (!usedFiles.has(op.name)) {
        usedFiles.set(op.name, new Set());
        usedExt.set(op.name, new Set());
      }
      usedFiles.get(op.name)!.add(name);
      usedExt.get(op.name)!.add(ext);
      usedCount.set(op.name, (usedCount.get(op.name) ?? 0) + 1);
    }
  }
}

const used = [...usedFiles.keys()];
const missing = used.filter((c) => !registered.has(c)).sort((a, b) => usedCount.get(b)! - usedCount.get(a)!);
const noopUsed = used.filter((c) => registered.has(c) && noop.has(c)).sort((a, b) => usedCount.get(b)! - usedCount.get(a)!);
const noopUnused = [...noop].filter((c) => !usedFiles.has(c) && opId(c) >= 12000).sort();

const row = (c: string) =>
  `| \`${c}\` | ${opId(c)} | ${band(opId(c))} | ${usedCount.get(c)} | ${usedFiles.get(c)!.size} | ${[...usedExt.get(c)!].sort().join(", ")} |`;
const where = (c: string) => `- \`${c}\` — ${[...usedFiles.get(c)!].sort().join(", ")}`;

const md = `# Builtins TODO — unimplemented & no-op engine commands

_Generated by \`tools/scancmds.mts\`: scans every script-bearing game file under
\`gamefiles/\` and diffs the engine commands they invoke against the builtins
registered in \`src/engine/builtins/\` and \`src/engine/interp.ts\`._

**Scope:** ${filesScanned} script-bearing files (\`.SET\`, \`.STG\`, \`.SHP\`, \`.PUP\`, \`.CST\`, \`.MOV\`, \`BOOTFILE\`).
**Distinct commands invoked:** ${used.length}. **Registered builtins:** ${registered.size}.

How dispatch works: a script call whose name has no registered builtin falls
through \`Interpreter.onUnknown\` and silently returns \`0\` (logged as \`? name(...)\`).
A no-op/stub is registered — so it neither errors nor logs — but does nothing.

Columns: **uses** = total invocations across the corpus; **files** = distinct
files; **types** = file extensions the command appears in.

---

## 1. Not implemented at all (${missing.length})

Fall through to \`onUnknown\` → return \`0\`.

| command | opcode | band | uses | files | types |
|---|---|---|---|---|---|
${missing.map(row).join("\n")}

### Where each is used
${missing.map(where).join("\n")}

---

## 2. Implemented as no-op / stub (${noopUsed.length})

Registered so scripts don't error, but the handler does nothing meaningful.

| command | opcode | band | uses | files | types |
|---|---|---|---|---|---|
${noopUsed.map(row).join("\n")}

### Where each is used
${noopUsed.map(where).join("\n")}

---

## 3. No-op / stub builtins never invoked by any script (${noopUnused.length})

Registered as stubs but no script in the corpus calls them — listed for
completeness; no action needed unless new content uses them.

${noopUnused.map((c) => `\`${c}\``).join(", ") || "_(none)_"}
`;

writeFileSync(OUT, md);
console.log(`scanned ${filesScanned} files; ${used.length} used; missing ${missing.length}, noop-used ${noopUsed.length}, noop-unused ${noopUnused.length}`);
console.log(`wrote ${OUT}`);
