/* GENERATED by tools/mapjumps.ts — do not edit.
 * 17 usable red areas over 8 deck plans, reaching 8 sets.
 * 15 more are gated on `debugging` and do nothing in a shipped game — left out.
 * Regenerate: npx tsx tools/mapjumps.ts
 */
import type { MapJump, MapPageButton } from "./mapjumps";

/** the deck each page is, as its own jumpbaby passes it to jumppapa: 1=bd 2=a 3=b 4=c 5=d 6=e 7=f 8=g */
export const MAP_JUMPS: MapJump[] = [
  { to: "gstair1", page: 1, deck: "bd", region: "Button27", arrive: ["scene17", "view47"] },
  { to: "gstair2", page: 2, deck: "a", region: "Button34", arrive: ["scene14", "view37"] },
  { to: "gstair3", page: 3, deck: "b", region: "Button38", arrive: ["scene16", "view44"] },
  { to: "gstair3", page: 4, deck: "c", region: "Button41", arrive: ["scene15", "view38"] },
  { to: "recept1c", page: 5, deck: "d", region: "Button42", arrive: ["scene12", "view27"] },
  { to: "stair1c1", page: 2, deck: "a", region: "Button32", arrive: ["scene55", "view74"] },
  { to: "stair1c1", page: 3, deck: "b", region: "Button35", arrive: ["scene43", "view46"] },
  { to: "stair1c2", page: 4, deck: "c", region: "Button40", arrive: ["scene112", "view116"] },
  { to: "stair2c", page: 1, deck: "bd", region: "Button46", arrive: ["scene45", "view63"] },
  { to: "stair2c", page: 2, deck: "a", region: "Button31", arrive: ["scene42", "view52"] },
  { to: "stair2c", page: 3, deck: "b", region: "Button37", arrive: ["scene42", "view52"] },
  { to: "stair2c", page: 4, deck: "c", region: "Button22", arrive: ["scene42", "view52"] },
  { to: "stair2c", page: 5, deck: "d", region: "Button22", arrive: ["scene42", "view52"] },
  { to: "stair2c", page: 6, deck: "e", region: "Button22", arrive: ["scene42", "view52"] },
  { to: "stair2c", page: 7, deck: "f", region: "Button22", arrive: ["scene13", "view28"] },
  { to: "turkstrs", page: 6, deck: "e", region: "Button43", arrive: ["scene12", "view23"] },
  { to: "turkstrs", page: 7, deck: "f", region: "Button44", arrive: ["scene10", "view16"] },
];

/** the page buttons, in page order — the same region name on every plan */
export const MAP_PAGE_BUTTONS: MapPageButton[] = [
  { page: 1, region: "Button18" },
  { page: 2, region: "Button19" },
  { page: 3, region: "Button12" },
  { page: 4, region: "Button13" },
  { page: 5, region: "Button14" },
  { page: 6, region: "Button15" },
  { page: 7, region: "Button16" },
  { page: 8, region: "Button17" },
];

/** the region that runs exitmap() — closes the map having gone nowhere */
export const MAP_EXIT_REGION = "Button20";
